networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/24

services:
  adguard:
    container_name: adguard
    build: adguard
    restart: unless-stopped
    hostname: adguard
    environment:
      - WG_ROUTE=10.8.0.0/24 via 10.3.0.3 # Adds a static route so that adguard knowns how to route the dns-responses back to the vpn-clients via the wg-easy container ip
      - TZ=${TIMEZONE}
    volumes:
      - "./config/adguard-work:/opt/adguardhome/work"
      - "./config/adguard-conf:/opt/adguardhome/conf"
    ports:
      - "53:53/tcp"     # DNS over TCP
      - "53:53/udp"     # DNS over UDP
      - "8080:80/tcp"   # Web UI/HTTP
      - "3000:3000"     # Web UI/HTTP during setup
      - "443:443/tcp"   # DNS over HTTPS (DoH)
      - "853:853/tcp"   # DNS over TLS (DoT)
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: 10.3.0.2

  wg-easy:
    depends_on: [adguard]
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=${VPN_ENDPOINT_ADDRESS}
      - PASSWORD_HASH=${WG_EASY_PASSWORD}
      - WG_PORT=${WIREGURAD_PORT}
      - WG_DEFAULT_DNS=10.3.0.2     # adguard-container ip
      - UI_TRAFFIC_STATS=true
      - WG_DEFAULT_ADDRESS=10.8.0.x # vpn-clients (peer) subnet 
      - WG_POST_UP=iptables -t nat -I POSTROUTING -d 10.3.0.2 -s 10.8.0.0/24 -j ACCEPT; iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport ${WIREGURAD_PORT} -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
      # OPTIONAL:
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.1.0/24, 10.3.0.0/24
    volumes:
      - "./config/wg-easy:/etc/wireguard"
    ports:
      - "${WIREGURAD_PORT}:${WIREGURAD_PORT}/udp"
      - "51821:51821/tcp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    networks:
      private_network:
        ipv4_address: 10.3.0.3

  duckdns:
      image: linuxserver/duckdns
      container_name: duckdns
      environment:
        - TOKEN=${DUCKDNS_TOKEN}
        - SUBDOMAINS=${DUCKDNS_SUBDOMAIN}
      restart: unless-stopped
      networks:
        private_network:
          ipv4_address: 10.3.0.4